---
name: Main
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        run: go test -v ./...
